//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_CRUD_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Categoria
    {
        public Categoria()
        {
            this.Gasto = new HashSet<Gasto>();
            this.Ingreso = new HashSet<Ingreso>();
        }
    
        public int CategoriaID { get; set; }
        [DisplayName("Categoria")]
        public string Nombre { get; set; }
    
        public virtual ICollection<Gasto> Gasto { get; set; }
        public virtual ICollection<Ingreso> Ingreso { get; set; }
    }
}
